version: '3.3'
services:
  
  frontend:
    image: mariavan88/foodgram_frontend:v1.0
    volumes:
      - ../frontend/:/app/result_build/

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres-db-data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  backend:
    image: mariavan88/foodgram_api:v1
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
      - docs:/app/api/docs/
    depends_on:
      - db
    env_file:
      - ./.env
  
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ./docs:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/

    depends_on:
      - backend

volumes:
  postgres-db-data:
  static_value:
  media_value:
  docs: