# Generated by Django 2.2.16 on 2023-03-19 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(default='шт', help_text='Ед. изм.', max_length=10, verbose_name='Ед.изм.')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
    ]
