# Generated by Django 2.2.16 on 2023-04-09 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20230407_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='color',
            field=models.CharField(max_length=7, verbose_name='цвет тега'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Название тега'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='слаг для тега'),
        ),
    ]
