# Generated by Django 2.2.16 on 2023-04-21 17:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20230422_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(max_length=200, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Название тега должносодержать только буквы русского алфавита', regex='^[А-Яа-я]+[^\\W\\d_]*[А-Яа-я]*$')], verbose_name='Название тега'),
        ),
    ]
