# Generated by Django 2.2.16 on 2023-04-16 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20230413_1739'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipes',
            options={},
        ),
    ]
